name: Workflow 3

on:
  workflow_run:
    workflows: ["Workflow 2"]
    types:
      - completed
      - sucess

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying after Workflow 2!" 
