name: Workflow 2

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      - success

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests after Workflow 1!"
